Enterprise/Controllers/HomeController.cs
using Enterprise.Modelos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Enterprise.Controllers
{
    public class HomeController : Controller
    {
        DCEnterpriseDataContext dc = new DCEnterpriseDataContext();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Sobre()
        {
            return View();
        }

        public ActionResult Servicos()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Servicos(Orcamento or)
        {
            if (ModelState.IsValid)
            {
                dc.Orcamentos.InsertOnSubmit(or);
            }

            try
            {
                dc.SubmitChanges();

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View();
            }
        }

    }
}

Enterprise/Controllers/NewslettersController.cs
using Enterprise.Modelos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Enterprise.Controllers
{
    public class NewslettersController : Controller
    {
        DCEnterpriseDataContext dc = new DCEnterpriseDataContext();

        // GET: Newsletters
        public ActionResult Index()
        {
            return View(dc.Newsletters);
        }

        // POST: Newsletters/Create
        [HttpPost]
        public ActionResult News(Newsletter novaNews)
        {
            if (ModelState.IsValid)
            {
                dc.Newsletters.InsertOnSubmit(novaNews);
            }
            try
            {
                dc.SubmitChanges();
                return RedirectToAction("Index","Home");
            }
            catch
            {
                return View();
            }
        }
    }
}

Enterprise/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Welcome";
}

<section id="boxes">
    <div class="container">
        <div class="box">
            <img src="~/Content/Imagens/logo_html.png" alt="logo 1">
            <h3>Jogos html 5</h3>
            <p>Com o html desenvolvemos jogos e aplicativos 2D, 3D, VR e AR</p>
        </div>
        <div class="box">
            <img src="~/Content/Imagens/logo_css.png" alt="logo 2">
            <h3>Jogos css</h3>
            <p>Desenvolvemos aplicativos corporativos, experiências cinematográficas e jogos</p>
        </div>
        <div class="box">
            <img src="~/Content/Imagens/logo_brush.png" alt="logo 3">
            <h3>Personagens</h3>
            <p>Fazemos as melhores personagens para videojogos de ultima geração</p>
        </div>
    </div>
</section>

Enterprise/Views/Home/Servicos.cshtml
@model Enterprise.Modelos.Orcamento
@{
    ViewBag.Title = "Serviços";
}
<section id="main">
    <div class="container">
        <article id="main-col">
            <h1 class="titulo">Serviços</h1>
            <ul id="servicos">
                <li>
                    <h3>Jogos Unity</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam molestias dolore ex incidunt facere nihil sint amet perferendis, ipsam, repellendus?</p>
                    <p>Preços: 1000&euro; - 3000&euro;</p>
                </li>
                <li>
                    <h3>Personagens</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam molestias dolore ex incidunt facere nihil sint amet perferendis, ipsam, repellendus?</p>
                    <p>Preços: 10&euro; - 300&euro;</p>
                </li>
                <li>
                    <h3>Jogos Unreal</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam molestias dolore ex incidunt facere nihil sint amet perferendis, ipsam, repellendus?</p>
                    <p>Preços: 1500&euro; - 4000&euro;</p>
                </li>
            </ul>
        </article>
        <aside id="sidebar">
            <div class="dark">
                <h3>Peça um orçamento</h3>
                @using (Html.BeginForm())
                {
                <div class="orcamento">
                    <div>
                        @Html.LabelFor(model => model.NomeCliente, "Nome")<br>
                        @Html.EditorFor(model => model.NomeCliente, new { htmlAttributes = new { type = "text", placeholder = "NomeCliente" } })
                    </div>
                    <div>
                        @Html.LabelFor(model => model.Email, "Email")<br>
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { type = "email", placeholder = "Email" } })
                    </div>
                    <div>
                        @Html.LabelFor(model => model.Mensagem, "Mensagem")<br>
                        @Html.TextAreaFor(model => model.Mensagem, htmlAttributes: new { placeholder = "Mensagem" })
                    </div>
                    <button type="submit" class="button_1">Enviar</button>
                </div>
                }
        </aside>
    </div>
</section>

Enterprise/Views/Home/Sobre.cshtml
@{
    ViewBag.Title = "Sobre";
}

<section id="main"></section>
<div class="container">
    <article id="main-col">
        <h1>Sobre Nós</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque magni nulla molestias fuga impedit quas numquam necessitatibus sint nemo vel. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Placeat, laudantium, quaerat. Sunt cum facere dicta explicabo quo. Reprehenderit, dolore, et?</p>
        <p class="dark">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quaerat cumque sit labore voluptate veritatis esse, sint assumenda, incidunt nostrum pariatur libero soluta dignissimos quam nihil exercitationem. Aspernatur possimus culpa laudantium nesciunt. Tempore est, quidem perspiciatis nulla ratione ab illum. Sed repellendus sunt, repellat quasi, saepe neque praesentium voluptatibus ad sequi.</p>
    </article>
    <aside id="sidebar">
        <div class="dark">
            <h3>O que fazemos</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut assumenda vel adipisci magnam, impedit facere amet accusantium repellendus delectus obcaecati esse laborum vitae dolore dicta voluptatibus, molestiae ipsum! Ullam numquam modi eum eos aut architecto.</p>
        </div>
    </aside>
</div>

Enterprise/Views/Shared/_Layout.cshtml
﻿@model Enterprise.Modelos.Newsletter

<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="Description" content="desenvolvimento de jogos e realidade virtual">
    <meta name="Keywords" content="realidade virtual, criamos jogos, desenvolvemos jogos">
    <meta name="author" content="cet 30">

    <title>Global Games | @ViewBag.Title</title>

    @Styles.Render("~/Content/css")
</head>

<body>

    <header>
        <div class="container">
            <div id="logo">
                <h1><span class="destaque">Global</span> Games Enterprise</h1>
            </div>
            <nav>
                <ul>
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sobre", "Sobre", "Home")</li>
                    <li>@Html.ActionLink("Serviços", "Servicos", "Home")</li>
                </ul>
            </nav>
        </div>
    </header>

    <section id="showcase">
        <div class="container">
            <h1>A melhor plataforma de realidade virtual</h1>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas laoreet odio ut augue accumsan, quis maximus magna sollicitudin. Fusce ut maximus magna, ut accumsan quam.
            </p>
        </div>
    </section>

    <section id="newsletter">
        <div class="container">
            <h1>Subscreva a nossa newsletter</h1>
            @using (Html.BeginForm("News", "Newsletters", FormMethod.Post))
            {
                <div >
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { type = "email", placeholder = "Email" } })
                    <button type="submit" class="button_1">Subscrever</button>   
                </div>
            }
        </div>
    </section>

    @RenderBody()

    <footer>
        <p>Global Games, Todos os direitos reservados &copy; @DateTime.Now.Year</p>
    </footer>

</body>
</html>